# Generated by Django 5.2 on 2025-04-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrisisSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('Emergency', 'Emergency'), ('Substance Abuse', 'Substance Abuse'), ('Youth Support', 'Youth Support'), ('LGBTQ+', 'LGBTQ+'), ('Other', 'Other')], max_length=50)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
