# Generated by Django 5.2 on 2025-04-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
